// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvpoxipuygxqqcdnjypg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2cG94aXB1eWd4cXFjZG5qeXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTMzNjYsImV4cCI6MjA3MDUyOTM2Nn0.c1OtnbFuT5n7OTUin89m_Eh0gAnspr4bZf0fGTSWVlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});